# Generated by Django 4.2 on 2023-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_shift_alter_account_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(null=True),
        ),
    ]
